### ISSUE TITLE
New structure

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/support-for-ect-data-extractor#1]
I have opted to make the new structure flatter than it could be to mimic how the current site works. We don't have pages for every 'node', so here's how the directories are nested so far:

```
output
├── ambition-institute
│  ├── year-1-behaviour
│  │  ├── autumn-week-1-ect-module-overview.md
│  │  ├── autumn-week-1-ect-reflect.md
│  │  ├── autumn-week-1-ect-video-and-module-introduction.md
│  │  ├── autumn-week-1-mentor-context-specific-meeting.md
│  │  ├── autumn-week-1-mentor-contracting-meeting.md
│  │  ├── autumn-week-2-ect-reflect.md
│  │  ├── autumn-week-2-ect-teaching-challenge.md
```

* `{provider}`
  * `year-{year_num}-{module`
    * `{term}-week-{week_num}-{type}-{name}.md`

It could be fully nested, like this:

* `{provider}`
  * `{year_num}`
    * `{module}`
      * `{term}`
        * `{week_num}`  
          * `{name}` 

But that would introduce levels where we don't currently have any pages/content.

It's trivial to change at this point but would be problematic later. Thoughts @EmmaFrith @frankieroberto?

**Comment by frankieroberto** [comment]
Does this structure map to the URLs? (ie each folder is a `/`) or are they independent?

Either way, the flatter structure looks good to me. We can always change later (and add redirects) if we find ourselves wanting to add extra pages at the intermediate levels. Generally though I prefer to avoid having a ton of index pages before you get to the actual content.

**Comment by peteryates** [comment]
The structure maps directly, so taking the top file as an example the page would be found at

`/ambition-institute/year-1-behaviour/autumn-week-1-ect-module-overview`

And the WIP example (frontmatter and titles will be added soon!):

![image](https://github.com/DFE-Digital/support-for-ect-data-extractor/assets/128088/ceed03c3-0ff1-44d8-8176-50cfeb5b2728)

**Comment by frankieroberto** [comment]
@peteryates cool. Flatter structure gets a 👍 from me.

**Comment by peteryates** [comment]
This is the approach I implemented.
